# start of Meshtastic configure yaml
canned_messages: Hi|Bye|Yes|No|Ok
channel_url: https://meshtastic.org/e/#CjISIPc9nMn64Eyni3Q9ptMKbyRFFIdTWh82dOcNb9S6SBCTGgpUQiBDUFMtUlRDOgIIDRIVCAEQBBj6ASAJKAU4BkACSAFQHmgB
config:
  bluetooth:
    enabled: true
    fixedPin: 123456
    mode: FIXED_PIN
  device:
    nodeInfoBroadcastSecs: 10800
    rebroadcastMode: LOCAL_ONLY
  display:
    screenOnSecs: 600
  lora:
    bandwidth: 250
    codingRate: 5
    hopLimit: 2
    modemPreset: MEDIUM_FAST
    region: ANZ
    spreadFactor: 9
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 30
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 300
    gpsMode: ENABLED
    gpsUpdateInterval: 300
    positionBroadcastSecs: 3600
    positionBroadcastSmartEnabled: true
    positionFlags: 811
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    privateKey: base64:0O59NPOC0qnNmuWsQnj8bqHZyQmEAgr63hgw3YKf3kk=
    publicKey: base64:6xBHJCaJB7i6+yLwcWWZRCblh0tD8sjwfWmsKsFYr20=
    serialEnabled: true
module_config:
  ambientLighting:
    blue: 78
    current: 10
    green: 13
    red: 254
  cannedMessage:
    enabled: true
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    password: large4cats
    root: msh/ANZ
    username: meshdev
  telemetry:
    deviceUpdateInterval: 120
    environmentMeasurementEnabled: true
    environmentUpdateInterval: 120
owner: Meshtastic 0d4e
owner_short: 0d4e

